version: 2
refs:
  executor: &executor
    docker:
      - image: cimg/go:1.16
  restore_go_modules_cache: &restore_go_modules_cache
      name: Restore go modules cache
      key: go-modules-cache-v1-{{ checksum "go.sum" }}
  download_go_modules: &download_go_modules
      name: Download go modules
      command: go mod download
  save_go_modules_cache: &save_go_modules_cache
      name: Save go modules cache
      key: go-modules-cache-v1-{{ checksum "go.sum" }}
      paths:
        - /go/pkg/mod/cache
jobs:
  test_lint:
    <<: *executor
    steps:
      - checkout
      - restore_cache: *restore_go_modules_cache
      - run: *download_go_modules
      - save_cache: *save_go_modules_cache
      - run:
          name: Lint
          command: go vet ./...
workflows:
  version: 2
  'Test and Lint':
    jobs:
      - test_lint


