version: 2.1
orbs:
  go: circleci/go@1.5.0
jobs:
  test_lint:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Lint
          command: go vet ./...
workflows:
  'Test and Lint':
    jobs:
      - test_lint
